name: Keep Alive CondoZap

on:
  schedule:
    # O cron roda a cada 10 minutos para garantir que o Render não durma (o limite é 15)
    # Formato: Minute Hour Day Month Day_of_Week
    - cron: '*/13 * * * *'
  workflow_dispatch: # Permite que você rode manualmente pelo painel do GitHub se quiser

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Server
        run: |
          curl -I -s https://condozap-vqsd.onrender.com/health || echo "Servidor demorou a responder, mas o ping foi enviado."
